/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockgetFileSystemsInfo.h"

typedef struct _CMOCK_getFileSystemsInfo_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  diskSpaceStatParce* ReturnVal;

} CMOCK_getFileSystemsInfo_CALL_INSTANCE;

static struct MockgetFileSystemsInfoInstance
{
  CMOCK_MEM_INDEX_TYPE getFileSystemsInfo_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockgetFileSystemsInfo_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.getFileSystemsInfo_CallInstance, cmock_line, "Function 'getFileSystemsInfo' called less times than expected.");
}

void MockgetFileSystemsInfo_Init(void)
{
  MockgetFileSystemsInfo_Destroy();
}

void MockgetFileSystemsInfo_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

diskSpaceStatParce* getFileSystemsInfo(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getFileSystemsInfo_CALL_INSTANCE* cmock_call_instance = (CMOCK_getFileSystemsInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getFileSystemsInfo_CallInstance);
  Mock.getFileSystemsInfo_CallInstance = CMock_Guts_MemNext(Mock.getFileSystemsInfo_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'getFileSystemsInfo' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void getFileSystemsInfo_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, diskSpaceStatParce* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getFileSystemsInfo_CALL_INSTANCE));
  CMOCK_getFileSystemsInfo_CALL_INSTANCE* cmock_call_instance = (CMOCK_getFileSystemsInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.getFileSystemsInfo_CallInstance = CMock_Guts_MemChain(Mock.getFileSystemsInfo_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

