/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKGETFILEPOINTFROMPOPEN_H
#define _MOCKGETFILEPOINTFROMPOPEN_H

#include "getFilePointFromPopen.h"

void MockgetFilePointFromPopen_Init(void);
void MockgetFilePointFromPopen_Destroy(void);
void MockgetFilePointFromPopen_Verify(void);




#define getFilePointFromPopen_ExpectAndReturn(pCmd, cmock_retval) getFilePointFromPopen_CMockExpectAndReturn(__LINE__, pCmd, cmock_retval)
void getFilePointFromPopen_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* pCmd, FILE* cmock_to_return);

#endif
